spring.application.name=api-prevencao-golpes

spring.datasource.url=jdbc:postgresql://192.168.56.101:5432/prevencao_golpes_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true